### ISSUE TITLE
Propose logo 

### ISSUE THREAD

**Issue by dee-y** [rjptegelaar/liquid-os#7]
Hello @paultegelaar @rjptegelaar, i am a graphic designer and i noticed your project does not have a logo yet. I like your project and would love to contribute a logo to it. Logo ideas are also welcomed...

Best regards, 
Dee-y.

**Comment by rjptegelaar** [comment]
Hey @dee-y,

All help is welcome :)

I am graphically handicapped, so I don't really have an idea. I can tell you the background of the name, maybe that will help. I am a huge Starcraft 2 fan, so I named the project after my favorite team, Team Liquid http://www.teamliquid.net/.

Regards,

Paul
